services:
  server:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./python:/python
  postgres:
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    image: "postgres:14-bullseye"
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume: {}
