services:
  server:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - ./python:/python
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: "postgres:14-bullseye"
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume: {}